extends Node
## Lang — jeu bilingue FR ⇄ EN, changé À CHAUD par le drapeau du menu.
## Le FRANÇAIS est la langue source : le code contient les textes français,
## et chaque affichage passe par Lang.t("texte") qui renvoie la traduction
## anglaise quand le joueur a choisi 🇬🇧. Un texte absent du dictionnaire
## s'affiche en français (jamais de trou, jamais de crash).

signal language_changed

## "fr" ou "en". Persisté avec la progression (voir GameConfig).
var locale := "fr"

func _ready() -> void:
	locale = GameConfig.language
	# Tests headless : `-- lang=en` force la langue sans toucher la sauvegarde.
	for arg in OS.get_cmdline_user_args():
		if arg.begins_with("lang="):
			locale = arg.get_slice("=", 1)

func t(text: String) -> String:
	if locale == "fr":
		return text
	return EN.get(text, text)

func toggle() -> void:
	locale = "en" if locale == "fr" else "fr"
	GameConfig.save_progress()
	language_changed.emit()

## Étiquette du bouton drapeau : montre la langue VERS laquelle on bascule.
func flag_label() -> String:
	return "🇬🇧 EN" if locale == "fr" else "🇫🇷 FR"

## Dictionnaire français → anglais. Rempli par familles d'écrans.
const EN := {
	"  (hôte)": "  (host)",
	"  (toi)": "  (you)",
	" (voisin)": " (neighbor)",
	" et ": " and ",
	"%s réagit : %s": "%s reacts: %s",
	"%s🏆 L'équipe %s remporte la partie !": "%s🏆 Team %s wins the game!",
	"(aucun)": "(none)",
	"(et TU en fais partie !)": "(and YOU'RE one of them!)",
	"(jeu en pause)": "(game paused)",
	"(la TIENNE !)": "(that's YOURS!)",
	"-10 PV, et les soins ne prennent plus sur toi pendant 20 s. Personne ne le sait…": "-10 HP, and healing won't work on you for 20 s. Nobody knows…",
	"-12 PV et tout ton écran tremble. Bzzzt.": "-12 HP and your whole screen shakes. Bzzzt.",
	"-2 PV par seconde pendant 10 secondes. Bon appétit.": "-2 HP per second for 10 seconds. Bon appétit.",
	"-2 PV/s pendant 5 s… pour toi ET tes deux voisins de table. Désolé les amis.": "-2 HP/s for 5 s… for you AND both your neighbors. Sorry, folks.",
	"-35 PV. Là, par contre, c'était une grosse grenade.": "-35 HP. Okay, THAT was a big grenade.",
	"-5 PV par seconde pendant 4 secondes. Ça pique.": "-5 HP per second for 4 seconds. That stings.",
	"Absolument Rien": "Absolutely Nothing",
	"Absorbe les 20 prochains points de dégâts. À garder en réserve.": "Absorbs the next 20 damage. Keep it in your back pocket.",
	"Adresse IP invalide. Exemple : 192.168.1.10 (ou 127.0.0.1 sur le même PC).": "Invalid IP address. Example: 192.168.1.10 (or 127.0.0.1 on the same PC).",
	"Ange Gardien": "Guardian Angel",
	"Au tour de %s…": "%s's turn…",
	"Aucune réponse de %s. Vérifie l'IP, le mot de passe, et que l'hôte a bien cliqué Héberger.": "No response from %s. Check the IP and password, and make sure the host actually clicked Host.",
	"Auréole": "Halo",
	"BOUM. -15 PV. Au moins, c'était une petite grenade.": "BOOM. -15 HP. At least it was a small one.",
	"Bleue": "Blue",
	"Bouclier": "Shield",
	"Brûlure": "Burn",
	"Béret": "Beret",
	"C'était peut-être ton enchaîné ? Oups.": "Was that your chained partner? Oops.",
	"Caillou de %s": "Rock from %s",
	"Carte du Destin": "Card of Fate",
	"Casque viking": "Viking Helmet",
	"Casquette": "Cap",
	"Chance": "Luck",
	"Chapeau pointu": "Pointy Hat",
	"Chaîne du destin": "Chain of fate",
	"Claque de %s": "Slap from %s",
	"Colère du barman": "Barman's wrath",
	"Connecté ! En attente du lancement par l'hôte…": "Connected! Waiting for the host to start…",
	"Connexion impossible : vérifie l'IP et que l'hôte a bien cliqué Héberger.": "Can't connect: check the IP and make sure the host clicked Host.",
	"Connexion impossible vers « %s ».": "Couldn't connect to “%s”.",
	"Connexion refusée : ": "Connection refused: ",
	"Couronne": "Crown",
	"Déconnecté par l'hôte.": "Disconnected by the host.",
	"E : se lever · ZQSD : marcher. Lis les cartes et les sacs par-derrière — ou clique un SAC pour tenter un VOL (crochetage) ! S'il se retourne : flagrant délit.\nDebout, tu peux être GIFLÉ, CAILLASSÉ… et si tu tardes à piocher : LAPIDATION. 🪨": "E: stand up · WASD: walk. Read cards and bags from behind — or click a BAG to attempt a STEAL (lockpicking)! If they turn around: caught red-handed.\nWhile standing you can get SLAPPED, PELTED… and if you stall on drawing: STONING. 🪨",
	"ENTRÉE : suivant · P : tout passer          %d / %d": "ENTER: next · P: skip all          %d / %d",
	"ESPACE : piocher · R : révéler · clic droit : utiliser · E : se lever · ZQSD : marcher · V : parler · T : chat · 1-4 : émotes · Échap : pause": "SPACE: draw · R: reveal · right click: use · E: stand up · WASD: walk · V: talk · T: chat · 1-4: emotes · Esc: pause",
	"Enchaînés : paires secrètes, si ton enchaîné meurt tu meurs · Équipes : Rouge vs Bleu, tir ami autorisé (4 joueurs min).": "Chained: secret pairs — if your chained partner dies, you die · Teams: Red vs Blue, friendly fire allowed (4 players min).",
	"Explosion": "Explosion",
	"Frisson": "Shiver",
	"Gaz toxique": "Toxic Gas",
	"Grenade lançable": "Throwable Grenade",
	"Haut-de-forme": "Top Hat",
	"Huile chaude": "Hot Oil",
	"IP de l'hôte (ex : 192.168.1.10) — pour rejoindre": "Host IP (e.g. 192.168.1.10) — to join",
	"Il ne se passe rien. Mais ce battement de cœur, tout le monde l'a entendu.": "Nothing happens. But everyone heard that heartbeat.",
	"Il ne se passe rien. Mais les autres ne le savent pas…": "Nothing happens. But the others don't know that…",
	"Il te faut ⭐ %d pour « %s » (réserve : %d). Joue avec audace !": "You need ⭐ %d for “%s” (stash: %d). Play bold!",
	"Impossible d'ouvrir le port %d (déjà utilisé ?)": "Couldn't open port %d (already in use?)",
	"Je vois TOUT.": "I see EVERYTHING.",
	"Joueurs connectés :": "Connected players:",
	"La prochaine mort ne sera pas la tienne : tu survis à 1 PV. Une seule fois.": "The next death won't be yours: you survive at 1 HP. One time only.",
	"Le barman t'aurait fait pire.": "The barman would've done worse.",
	"Le but : être le DERNIER SURVIVANT (100 PV chacun).\nÀ ton tour, pioche une carte : ESPACE, ou clique sur la pioche qui brille.\nElle peut être bénéfique 💚, dangereuse 💥, piégée… ou n'être Absolument Rien 👻.": "The goal: be the LAST ONE STANDING (100 HP each).\nOn your turn, draw a card: SPACE, or click the glowing deck.\nIt might be helpful 💚, dangerous 💥, booby-trapped… or Absolutely Nothing at all 👻.",
	"Les cartes gardées (Médikit, Bouclier, Grenade lançable…) vont dans ton sac :\nmolette pour choisir, clic droit pour utiliser — ou LANCER sur un joueur visé.\nMéfiance : la poche arrière est transparente, ton jeu se lit dans ton dos !": "Cards you keep (Medkit, Shield, throwable Grenade…) go in your bag:\nscroll wheel to select, right-click to use — or THROW it at a targeted player.\nBeware: the back pocket is see-through, your hand can be read behind your back!",
	"Ma grand-mère bluffe mieux que toi.": "My grandma bluffs better than you.",
	"Malédiction": "Curse",
	"Mini-grenade": "Mini Grenade",
	"Mort subite": "Sudden death",
	"Mot de passe de la partie (optionnel)": "Game password (optional)",
	"Mot de passe incorrect.": "Wrong password.",
	"Médikit": "Medkit",
	"On applaudit bien fort.": "A big round of applause.",
	"Poison": "Poison",
	"Pris la main dans le sac": "Caught red-handed",
	"Que le meilleur menteur gagne.": "May the best liar win.",
	"Quitter": "Quit",
	"Quitter le jeu": "Quit game",
	"Quitter le salon": "Leave the room",
	"Rien de personnel.": "Nothing personal.",
	"Rouge": "Red",
	"Soigne 30 PV. À garder pour le bon moment.": "Heals 30 HP. Save it for the right moment.",
	"Soin, bouclier, audace… ou rien du tout. La chance est capricieuse.": "Healing, shield, boldness… or nothing at all. Luck is fickle.",
	"Sombrero": "Sombrero",
	"Toi seul vois ta carte : joue la comédie avec les émotes (touches 1 à 4) !\nPendant que tu la lis, la touche R la RÉVÈLE à tous : +1 point d'audace et +3 PV.\nL'audace départage les doubles KO — et fait ta légende.": "Only you can see your card: put on a show with emotes (keys 1 to 4)!\nWhile reading it, press R to REVEAL it to everyone: +1 daring point and +3 HP.\nDaring breaks double-KO ties — and builds your legend.",
	"Ton message… (Entrée : envoyer · Échap : annuler)": "Your message… (Enter: send · Esc: cancel)",
	"Toque de chef": "Chef's Hat",
	"Tu es condamné. Tu ne sais pas quand. Bonne chance.": "You are doomed. You don't know when. Good luck.",
	"Tu l'as bien cherché.": "You had it coming.",
	"Tu trembles déjà ?": "Shaking already?",
	"UNE seule fleur par partie : offre-la à quelqu'un (+30 PV)… ou garde-la pour toi.\nLe billard rapporte des points d'audace. Colle-toi à un blessé : son cœur bat.\nEt surtout : NE DÉRANGEZ. PAS. LE BARMAN.": "ONE single flower per match: give it to someone (+30 HP)… or keep it for yourself.\nPool earns daring points. Get close to a wounded player: you'll hear their heartbeat.\nAbove all: DO NOT. DISTURB. THE BARMAN.",
	"Un bruit étrange retentit…": "A strange noise rings out…",
	"Vampirisme": "Vampirism",
	"Verrou %d / %d — ESPACE dans la zone verte · Échap : renoncer": "Lock %d / %d — SPACE in the green zone · Esc: give up",
	"Versions différentes (hôte %s, toi %s) : téléchargez la même release !": "Version mismatch (host %s, you %s): download the same release!",
	"Vite, avant qu'il ne se retourne…": "Quick, before they turn around…",
	"Vole 12 PV à un joueur visé. Ils sont à TOI maintenant.": "Steals 12 HP from a targeted player. They're YOURS now.",
	"cette carte": "this card",
	"rien du tout": "nothing at all",
	"À lancer sur la tronche d'un adversaire : -20 PV à l'impact.": "Chuck it at someone's face: -20 HP on impact.",
	"À partager avec tes amis :\nIP : %s   ·   Mot de passe : %s\n(sur le même PC : 127.0.0.1)": "Share this with your friends:\nIP: %s   ·   Password: %s\n(same PC: 127.0.0.1)",
	"Ça éclabousse et ça brûle : -4 PV/s pendant 4 s sur la cible.": "It splashes and it burns: -4 HP/s for 4 s on the target.",
	"ÉCHANGE tes PV avec ceux du joueur visé. À utiliser mourant, évidemment.": "SWAPS your HP with the targeted player's. Best used while dying, obviously.",
	"Échange Vital": "Vital Swap",
	"Électrocution": "Electrocution",
	"⏳ Connexion à %s…": "⏳ Connecting to %s…",
	"⏳ En attente des autres joueurs…": "⏳ Waiting for the other players…",
	"⏳ Encore en train de lire le tutoriel : %s": "⏳ Still reading the tutorial: %s",
	"⏸️  Pause": "⏸️  Paused",
	"▶   JOUER EN SOLO": "▶   PLAY SOLO",
	"▶   Reprendre": "▶   Resume",
	"☘️ Chanceux : +2 points d'audace !": "☘️ Lucky: +2 boldness points!",
	"☘️ Chanceux : +30 PV !": "☘️ Lucky: +30 HP!",
	"☘️ Chanceux : bouclier de 25 !": "☘️ Lucky: 25 shield!",
	"☘️ …rien. La chance est capricieuse.": "☘️ …nothing. Luck is fickle.",
	"☣️ Le gaz se répand sur les voisins de %s !": "☣️ The gas spreads to %s's neighbors!",
	"⚔️  Mode de jeu": "⚔️  Game mode",
	"⚔️ Dernière équipe debout gagne. Le tir ami existe. Bonne chance.": "⚔️ Last team standing wins. Friendly fire is on. Good luck.",
	"⚔️ L'équipe %s remporte la partie !": "⚔️ Team %s wins the game!",
	"⚔️ Équipes": "⚔️ Teams",
	"⚔️ 🔴 Équipe Rouge : %s": "⚔️ 🔴 Red Team: %s",
	"⚔️ 🔵 Équipe Bleue : %s": "⚔️ 🔵 Blue Team: %s",
	"⚖️ Double KO ! L'audace départage : %s l'emporte avec %d point%s !": "⚖️ Double KO! Boldness breaks the tie: %s wins with %d point%s!",
	"⚠️ La partie continue : tu restes vulnérable à la table !": "⚠️ The game goes on: you're still fair game at the table!",
	"⚠️ QUELQU'UN FOUILLE TON SAC !! ⚠️": "⚠️ SOMEONE'S RIFLING THROUGH YOUR BAG!! ⚠️",
	"⚠️ Statut subi : %s": "⚠️ Status inflicted: %s",
	"⚡ Les lumières de la taverne s'éteignent d'un coup !": "⚡ The tavern lights suddenly go out!",
	"⛓️ %s s'effondre soudain… il était enchaîné à %s !": "⛓️ %s suddenly collapses… they were chained to %s!",
	"⛓️ Enchaînés jusqu'au bout : %s remportent la partie ENSEMBLE !": "⛓️ Chained to the very end: %s win the game TOGETHER!",
	"⛓️ INDICES : quand il encaisse, tu le SENS (bannière + cœur) → regarde qui vient d'être touché. Et à moins de 2 m de lui, ta chaîne frémit.": "⛓️ CLUES: when they take a hit, you FEEL it (banner + heart) → watch who just got hurt. And within 2 m of them, your chain quivers.",
	"⛓️ Les Enchaînés": "⛓️ The Chained",
	"⛓️ Ta chaîne frémit": "⛓️ Your chain shivers",
	"⛓️ Ta chaîne frémit… il est tout près.": "⛓️ Your chain shivers… they're close by.",
	"⛓️ Ta chaîne frémit… ton enchaîné est TOUT PRÈS.": "⛓️ Your chain quivers… your chained partner is VERY CLOSE.",
	"⛓️ Tu es enchaîné à quelqu'un dans cette salle… S'il meurt, tu meurs.": "⛓️ You are chained to someone in this room… If they die, you die.",
	"⛓️🏆 %s remportent la partie ENSEMBLE !": "⛓️🏆 %s win the game TOGETHER!",
	"⛔ Ce n'est pas ton tour !": "⛔ It's not your turn!",
	"✅ Tutoriel déjà lu — tu es prêt !   (P : le relire)": "✅ Tutorial already read — you're ready!   (P: read it again)",
	"✨ %s utilise %s %s.": "✨ %s uses %s %s.",
	"❗ On t'a volé : %s %s !": "❗ Someone stole your %s %s!",
	"⭐ %d point%s d'audace": "⭐ %d daring point%s",
	"⭐ +%d d'audace en réserve (total : %d) — dépense-les au menu !": "⭐ +%d daring banked (total: %d) — spend it in the menu!",
	"⭐ 0 point d'audace": "⭐ 0 daring points",
	"🃏 %s pioche une carte…": "🃏 %s draws a card…",
	"🌐  Multijoueur — héberge, ou rejoins avec IP + mot de passe": "🌐  Multiplayer — host a game, or join with IP + password",
	"🌟 Céleste": "🌟 Celestial",
	"🌩️ Un orage éclate au-dessus de la taverne !": "🌩️ A storm breaks out above the tavern!",
	"🌹 %s cueille l'unique fleur de la taverne… Pour qui ?": "🌹 %s picks the tavern's only flower… Who's it for?",
	"🌹 %s offre sa fleur à %s ! Toute la table fond. (+30 PV, +1 audace chacun)": "🌹 %s gives their flower to %s! The whole table melts. (+30 HP, +1 boldness each)",
	"🌹 Approche-toi de lui pour offrir ta fleur !": "🌹 Get closer to give them your flower!",
	"🌹 La taverne vit": "🌹 The tavern is alive",
	"🌹💅 %s s'offre la fleur à LUI-MÊME ! +30 PV, et aucune honte.": "🌹💅 %s gives the flower to THEMSELF! +30 HP, zero shame.",
	"🍺 %s s'accorde un verre au comptoir. (+1 PV)": "🍺 %s enjoys a drink at the bar. (+1 HP)",
	"🍺 Le barman essuie encore ton verre… (patiente un peu)": "🍺 The barman is still wiping your glass… (hang on a bit)",
	"🍺 Le barman lève les yeux : « Ne m'énerve pas. »": "🍺 The barman looks up: \"Don't push me.\"",
	"🍺 Le barman t'ignore pendant le tutoriel.": "🍺 The barman ignores you during the tutorial.",
	"🍺 « ATTENTION. Le prochain coup, je m'énerve. »": "🍺 \"WARNING. One more and I lose my temper.\"",
	"🍺 « DERNIER AVERTISSEMENT. Encore un clic et je t'emporte, toi et deux autres. »": "🍺 \"FINAL WARNING. One more click and I take you down, plus two others.\"",
	"🍺 « J'ai dit : ne. m'énerve. PAS. »": "🍺 \"I said: do. NOT. push me.\"",
	"🎒 %s range une carte dans son sac…": "🎒 %s tucks a card into their bag…",
	"🎒 Ton sac (et celui des autres)": "🎒 Your bag (and everyone else's)",
	"🎤  Micro activé (maintenir V pour parler)": "🎤  Microphone on (hold V to talk)",
	"🎨  Ta couleur": "🎨  Your color",
	"🎩  Ton chapeau — réserve : ⭐ %d": "🎩  Your hat — stash: ⭐ %d",
	"🎭 Le bluff, c'est le jeu": "🎭 Bluffing is the game",
	"🎯 Vise un joueur pour utiliser %s !": "🎯 Aim at a player to use %s!",
	"🎯 À TOI !": "🎯 YOUR TURN!",
	"🎯 À TOI DE PIOCHER !\nESPACE — ou clique sur la pioche qui brille": "🎯 YOUR TURN TO DRAW!\nSPACE — or click the glowing deck",
	"🎯 À TOI — appuie sur ESPACE pour piocher": "🎯 YOUR TURN — press SPACE to draw",
	"🎱 %s empoche une bille ! (+1 point d'audace)": "🎱 %s pockets a ball! (+1 boldness point)",
	"🎱 Une bille tombe dans la poche…": "🎱 A ball drops into the pocket…",
	"🎴  LANCER  (%d joueur%s + %d bot%s)": "🎴  START  (%d player%s + %d bot%s)",
	"🎴 %s %s gardée en main (clic droit pour l'utiliser).": "🎴 %s %s kept in hand (right click to use).",
	"🎴 Aucune carte en réserve.": "🎴 No cards in reserve.",
	"🎴 Bienvenue à la taverne !": "🎴 Welcome to the tavern!",
	"🎴 Dernière Carte": "🎴 Last Card",
	"🎴 GO !": "🎴 GO!",
	"🎴 La partie commence ! Que le meilleur menteur gagne.": "🎴 The game begins! May the best liar win.",
	"🎴 Main :": "🎴 Hand:",
	"🎴 Salle d'attente": "🎴 Waiting Room",
	"🏆 %s remporte la Dernière Carte !": "🏆 %s wins the Last Card!",
	"🏆 TU remportes la Dernière Carte !": "🏆 YOU win the Last Card!",
	"🏠  Héberger": "🏠  Host",
	"🏠  Menu  (M)": "🏠  Menu  (M)",
	"🏠  Menu principal": "🏠  Main menu",
	"🐔 Attendez… IL PLEUT DES POULETS ?!": "🐔 Wait… IS IT RAINING CHICKENS?!",
	"👀 %s se lève de sa chaise…": "👀 %s gets up from their chair…",
	"👀 Debout, tout se paie": "👀 On your feet, everything has a price",
	"👋 CLAC ! %s gifle %s !": "👋 SLAP! %s slaps %s!",
	"👤  Ton nom": "👤  Your name",
	"👻 Maudit : les soins ne prennent plus sur toi pendant %d s…": "👻 Cursed: healing won't work on you for %d s…",
	"👻 Mode spectateur — souris : orbiter · molette : zoomer.": "👻 Spectator mode — mouse: orbit · wheel: zoom.",
	"👼 L'Ange Gardien arrache %s à la mort !": "👼 The Guardian Angel snatches %s from death!",
	"👼 Un ange veille sur toi : la prochaine mort ne sera pas la tienne.": "👼 An angel watches over you: the next death won't be yours.",
	"💀 %s est hors-jeu ! (%s)": "💀 %s is out! (%s)",
	"💀 MORT SUBITE": "💀 SUDDEN DEATH",
	"💀 MORT SUBITE ! La taverne réclame un vainqueur — la vie de chacun s'écoule…": "💀 SUDDEN DEATH! The tavern demands a winner — everyone's life is draining away…",
	"💀 MORT SUBITE — la vie de chacun s'écoule !": "💀 SUDDEN DEATH — everyone's life is draining away!",
	"💀 Personne n'a survécu…": "💀 Nobody survived…",
	"💀 Personne n'a survécu… La table gagne.": "💀 Nobody survived… The table wins.",
	"💓 Un battement de cœur sourd résonne sous la table…": "💓 A muffled heartbeat throbs under the table…",
	"💚 +%d PV": "💚 +%d HP",
	"💡 La lumière revient…": "💡 The lights come back on…",
	"💥 %s lance %s %s sur %s !": "💥 %s throws %s %s at %s!",
	"💥 -%d PV (%s)": "💥 -%d HP (%s)",
	"💥 LE BARMAN EXPLOSE DE RAGE ! Il jette ses verres à travers la salle !": "💥 THE BARMAN EXPLODES WITH RAGE! He hurls his glasses across the room!",
	"💥 Toute la taverne se met à trembler !": "💥 The whole tavern starts shaking!",
	"💬 %s : %s": "💬 %s: %s",
	"📣 %s révèle sa carte : %s %s ! (+1 point d'audace)": "📣 %s reveals their card: %s %s! (+1 boldness point)",
	"🔄  Rejouer  (R)": "🔄  Play Again  (R)",
	"🔄 %s ÉCHANGE sa vitalité avec %s !": "🔄 %s SWAPS health with %s!",
	"🔊  Volume : %d %%": "🔊  Volume: %d %%",
	"🔊 Un bruit de goupille retentit quelque part autour de la table…": "🔊 The sound of a grenade pin echoes somewhere around the table…",
	"🔊 Un grondement sourd parcourt la taverne…": "🔊 A low rumble rolls through the tavern…",
	"🔍 Tu jettes un œil au sac de %s : il contient %s.": "🔍 You peek into %s's bag: it holds %s.",
	"🔗  Rejoindre": "🔗  Join",
	"🖥️  Plein écran": "🖥️  Fullscreen",
	"🖱️  Sensibilité souris : ×%.1f": "🖱️  Mouse sensitivity: ×%.1f",
	"🗡️ Chacun pour soi": "🗡️ Free-for-all",
	"🗣️  Volume des voix : %d %%": "🗣️  Voice volume: %d %%",
	"😈 Difficile": "😈 Hard",
	"😤 %s a surpris %s la main dans son sac !": "😤 %s caught %s with a hand in their bag!",
	"😤 FLAGRANT DÉLIT ! Tu t'es fait surprendre.": "😤 CAUGHT RED-HANDED! You got spotted.",
	"😮‍💨 %s pioche enfin. On repose les cailloux.": "😮‍💨 %s finally draws. Everyone put the rocks down.",
	"😴 Facile": "😴 Easy",
	"🙂 Moyen": "🙂 Normal",
	"🤖  Difficulté des bots": "🤖  Bot difficulty",
	"🤖 %s a quitté la partie — un bot prend le relais.": "🤖 %s left the game — a bot is taking over.",
	"🥀 Il n'y a plus de fleur à offrir cette partie…": "🥀 There are no flowers left to give this round…",
	"🩸 Ton enchaîné vient d'encaisser ! Qui a été touché à l'instant ?": "🩸 Your chain-mate just took a hit! Who got hurt just now?",
	"🩸 Une douleur sourde te traverse… ton enchaîné vient d'encaisser.": "🩸 A dull pain shoots through you… your chained partner just took a hit.",
	"🪑  Joueurs à table : %d": "🪑  Players at the table: %d",
	"🪑 %s se rassoit.": "🪑 %s sits back down.",
	"🪑 Reviens t'asseoir pour piocher ! (touche E)": "🪑 Get back in your seat to draw! (press E)",
	"🪨 %s fait traîner la partie… Caillassage autorisé jusqu'à ce qu'il pioche !": "🪨 %s is stalling the game… Rock-throwing is allowed until they draw!",
	"🪨 LAPIDATION AUTORISÉE sur %s ! (clic gauche) 🪨": "🪨 STONING ALLOWED on %s! (left click) 🪨",
	"🪨 PIOCHE !!!": "🪨 DRAW!!!",
	"🪨 TU TE FAIS LAPIDER — PIOCHE !! 🪨": "🪨 YOU'RE BEING STONED — DRAW!! 🪨",
	"🪨 ÉCHAUFFEMENT — défoulez-vous, tout sera pardonné !": "🪨 WARM-UP — go wild, all will be forgiven!",
	"🫳 Fouille du sac de %s…": "🫳 Rifling through %s's bag…",
	"🫳 Interrompu en plein travail ! Le sac s'est refermé.": "🫳 Interrupted mid-job! The bag snapped shut.",
	"🫳 La cible s'est éloignée. Tentative annulée.": "🫳 The mark walked away. Attempt cancelled.",
	"🫳 Le sac de %s est ouvert. Choisis TA carte :": "🫳 %s's bag is open. Pick YOUR card:",
	"🫳 Le sac de %s est vide.": "🫳 %s's bag is empty.",
	"🫳 Le sac s'est refermé il y a peu… patiente un peu.": "🫳 That bag snapped shut not long ago… give it a moment.",
	"🫳 Lève-toi (E) pour tenter un vol.": "🫳 Stand up (E) to attempt a steal.",
	"🫳 Raté ! Le sac s'est refermé d'un coup sec.": "🫳 Missed! The bag snapped shut tight.",
	"🫳 Ton propre sac est plein !": "🫳 Your own bag is full!",
	"🫳 Tu renonces discrètement.": "🫳 You quietly back off.",
	"🫳 Une carte a été dérobée dans le sac de %s !": "🫳 A card was swiped from %s's bag!",
	"🫳 Volé : %s %s. Personne ne t'a vu… normalement.": "🫳 Stolen: %s %s. Nobody saw you… probably.",
}
